version: '3'
services:
  db:
    image: postgres
    volumes:
      - ../tmp/db:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build: .
    command: rackup --host 0.0.0.0 --port 9292
    volumes:
      - ./:/myapp
    ports:
      - "9292:9292"
    depends_on:
      - db
    env_file:
      - .env
